idf_component_register(
    SRCS 
        "ota/ota.c"
        "wifi/wifi.c"
        "mqtt/mqtt.c"
        "ble/ble.c"
        "flash/flash.c"
        "m_state_machine/m_state_machine.c"
    INCLUDE_DIRS 
        "ota"
        "wifi"
        "mqtt"
        "ble"
        "flash"
        "m_state_machine"
        "."
    REQUIRES 
        esp_https_ota
        esp_http_client
        app_update
        esp_wifi
        nvs_flash
        mqtt
        esp-tls
        mbedtls
        bt
        esp_timer
        third_party
    PRIV_REQUIRES
        hardware
)
